spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.metadata_builder_contributor: io.github.acoboh.query.filter.jpa.contributor.QfMetadataBuilderContributor